engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 350
    exclude_paths:
      - '**/tests'
  eslint:
    enabled: true
    channel: eslint-2
  fixme:
    enabled: true
ratings:
  paths:
    - '**.css'
    - '**.inc'
    - '**.js'
    - '**.jsx'
    - '**.es6'
    - '**.module'
exclude_paths:
  - '**/bin'
  - '**/test'
  - '**/tests'
  - '**/tmp'
  - '**/vendor'
  - '**/.idea'
  - '**/frontend/demo-pages'
  - '**/frontend/_build'
  - '**.spec.js'
  - '**.min.js'
  - '**.min.css'
  - '**/dist'
  - '**/node_modules'
  - '**/packages'
  - '**/frontend/css/vendor'
  - '**/frontend/js/vendor'
