engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 350
    exclude_paths:
      - '**/tests'
  eslint:
    enabled: true
    channel: eslint-2
  fixme:
    enabled: true
ratings:
  paths:
    - '**.css'
    - '**.inc'
    - '**.js'
    - '**.jsx'
    - '**.es6'
    - '**.module'
exclude_paths:
  - '**/bin'
  - '**/test'
  - '**/tests'
  - '**/tmp'
  - '**/vendor'
  - '**/aws-262'
  - '**/.idea'
  - '**/assets'
  - '**/nytimes'
  - '**/bloomberg'
  - '**/wapost'
  - '**/atm-build'
  - '**.spec.js'
  - '**.min.js'
  - '**.min.css'
  - '**/frontend/_build'
  - '**/frontend/js'
  - '**/dist'
  - '**/node_modules'
  - '**/packages'
  - '**/font-awesome.css'
  - '**/materialdesignicons.css'
  - '**/DeepFramework.js'
  - '**/deep-framework.js'
  - '**/src/deep-root-*'
  - '**/carousel.js'
  - '**/contact.js'
  - '**/gtm.js'
  - '**/jquery.js'
  - '**/jquery.noty.packaged.js'
  - '**/jquery.vide.js'
  - '**/input-mask.js'
  - '**/sw.js'
