language: node_js
dist: trusty
git:
  depth: 1
cache:
  bundler: true
  directories:
    - node_modules
    - "$(npm root -g)"
    - "$(npm config get prefix)/bin"
branches:
  only:
    - master
    - stage
    - test
    - build
    - dev
env:
  global:
    - DEEP_NO_INTERACTION=1
    # AWS_ACCOUNT_ID=[secure]
    - secure: "neCWR2sd07qIJ3PmW99Snp7r/0GdBrkFTnUfUmzCGWbq0FkX6MgbGK8Mnz/EWNpnZ07XiV816+/KGWFddisLYMCsbHoIFklBw5Z1ApWr9ZladEqoYeuCoM5KoDXkilwF6Zg3W66I+lOm0hwj73AyqO6iWtF8qZMZoIeUCYXBYTDLNBTUQTWJQyk34O4Umn8/f6FjCx/K0wJwQnA9NjqHYn2yKUEQR1Pu1ZPX95z90xEqiNEpu4AChohfLyGLeOoSSMiVTqftLXcqhOpK7WJnf5Mx/SWDhftpYtxYzHJ/QRqC9eomThvZoYMy6+yIV+HBvovlQCtOFRH+zkYZn9JmFigiAmr/BJx21eAfY07pPJvGR3uyGoR7NIXwCZZvck6U8mPzzueVLZSQZHqr1LZ+YkL52xc78OmyOMVft++chaBJGvLah4i8zRAf0frQHYPWqBBJyIysdS6/fGa2S0GaSDJugaSTYk4Lg1sGFxMZNQXK7Xos/DqQA6biNdWUPzCX9+YPMZNyv3MQtThDZDac6Feum6U9fylLKIJSrQJswMQoXzKT23GqGQnx0qrrz24l9KEyB+1oJ8byChd/IERnWjB+qrE4fB/acw2rA2iSAu0ZnohZq4W99ZpQYh8GVAMKuFD1t8Ex9M/fFIYkVl2/bEvjrceOQGDCwmQJCPIkCL8="
    # AWS_ACCESS_KEY_ID=[secure]
    - secure: "LCK0MqlPGhY1u7I/60GeZKuBC95rvVZSSE6xlxkG8hsXbiNGpxmmDE275NTHfPxKon2Kqvat2kN7e2si+wevMzH7Sb0wmcIaagqt+A8p4VCbCrtU3bbX6NyQjPDGkbzR0AS6ESFVP8+W7/qqDk6ZcFg9t1o3+u3eNyUu8RKnXnGnO/8SS7PPzCcmB4fU7f9beXbmoHqI3KKvAnlWcNTe+pdriIgCV/hGI+FnZ2Ped9th1VNOCp4h4Ye5nfibcuaQUYdXFOS+sT/DerFBWP2/BrOeU6W5M2+fJxia8e9xW00LsyRTukJGKdgnFfV05PhjgqrsrN6WoWkcC/+albO29XC5M+psZXoQnYIik3NVRvy8S+1HaGUPJqUBZEnmmPrK58xBNX9X09fu5ngUdhqi35BRJIqlE2zKJ65GY1aUqpmt7UOvMF1nfcQ3BWitN8ubg6mG5MwOsmcV8DNVjO11XSrR9rPfPLVcN22DqQi0sE0U7r7NGzrE7nztWdswui9PWscxklghDepAH74B4O9cTfz1T89G4+1GyV0eOXqvv0zbc4NAPLEkJatljSYxHp5k0YrQgh5C3nMs3qNkje0QeYo9vxRd6Vm81goK5tMR6QnGCEUwIdD1tYYKILoeEc7jNkCXs7nOSEcUsL0SPn/Qd74gCBtMctMBbMUDLWfAv9A="
    # AWS_SECRET_ACCESS_KEY=[secure]
    - secure: "J2ZkKnRlzyRAc+sKGAEIGJhqtLi+bbzcfUQ8b7eKnG7w6oLNIbfJKnCbr9Fvu6L3UwfnzT7G2n+PkyJb0xdvTF7s/MEkPZmMeVjViTQsXzh2QAdKECun3LiRRhZHf4wMYviJYUgQjk1eOUqOieXV+/GwOuglsyNg4Dpir0u5zHZwdDiMVvqgEF5WjPs0qtcLsabrDHIKhapb8qXSEZBDWUfIkbZ7xdVdPdqYL1a9hr4zyOCXchr4KBfenraFT5kOILpuLEC6hLVGmzP0u5tOfYsG2UP8CW482DVPoRIhDLJ5w3Ofj1NRUQ59x+2Z8T4OhFqxP90ItnPCOIP8o/gj0eC1s/Ab3na7Fr8QhfJrDc+FIgpNNo/wSyCe2bXqcSSSvAe5rngY0Un7AEmwLxh7oLAc/rgGpcY6W3MG9QWVkX1mP1I2sOS5euL0TiXBZISpnQkjt6Gbz5+wE5G3i5iJxudcAkqZOhk+8EJ7wOmpx1b4qKzPbiWYRwJpWHzcUq2xZUciFfUo6vQ9VguISnuBmVKZNKDdUgNaK52j/SAgnc0tpVvamJ+VLWYlv2d5YlblvG8RiUlAJJt9H0ZVSoktiNhYam1Z8Tk8aKr4cAK+UK66MGm7W61sj2jNnc7KQb4liizCGjwwH1sUGWNItqX0gLTXJwnHgNqtXFOg0MxN8PU="
    # AWS_DEFAULT_REGION=[secure]
    - secure: "gWJrmDW/p0y9KHcFulgiHXayZQluRZMducNhRLMn6yT0oc8pOPDQSULg/N02PTXycyNCAJxRAWlH6DD6y5rJjfvSqVU5e8b3fn/sGSL1uZQniWN7zt/yoaiYnTXDEtlKl2bhJw78WdQpWmS69TrlNWkIsmCod9c/gVpMm03AcE8isfqmeEqgV8ENQQjPHiXqgc/TFcMb5XC3nKKCg+0SdAXtV56qfE7fR1b+EOsLzHB8xUSHtEceZDV6G+ufmrts+o7j6vGfmonGv3kXgtd3/Nzyortr+yatx6DNhj/3xRX2N1xqSJ6XUJ0Ac6UyJfnaMCi/mZJV9i23nVsymV6GWIIVw7I6bEJLgh9rHfe1mCIDRDEO0BoR2K2v/GAAIrYbI0iKxxgVJesO/a10t33t2fnif905794KVM1ZcP46e0R6kD2qiF04b86sPtXGkXa5HQSRZ3rSDJQqAb1r+Ls/jWK4xm7Xt/3p267dKnBc1KGMZD4CjMJHw8wO3lKX3whS/zC4OvYlgjobetKoKfT4VNHGQ/RWxCLYLWIKh6tLXVkKbFbis1IlXIiCfwQFTfZaJ1co/I2HXbLfAJ3LE6PNCDD5u8b8+0K0nYuLvpoAPjcw/W+RkHP8CQtRNBgCGup1nWtoYBTQ+mb57YbO1R5F6iZjNuB4RVy01LQ3jqpXeT4="
    # CODECLIMATE_REPO_TOKEN=[secure]
    - secure: "QONsxWDu0hlTbrTdM2u1ay2tKsIesz56UKjwNanSD3TyBkAvib2w/BZXZL2QuLkNm4nUYrWGrxDNDn4EQbfNKOvo3d3IUI0W+ZDwrKAGKVa8SOXCiXCuh5gXJnbkuLBAS3Mj+EznZ/GCNieWw+4N3iAjXwUJiaAFvyC1hzNsY3Sh+vDJjjmqJZC63kc8rfO+aWb0oRm1m7rnd6weHJBw8F6M2u4DS9N+zCu1UcOufzalcjh3+8isgwkbHVLVDOtNPdGI/Kv6J+kL66K1yhWlKWlV4IfEoOM4iYpo9vYafeLROLOcTnTHFJ7glZM2HU+83mfSu1RvWwUPVz05o0bF6nkM2Fy+Go+qmQHf7AJ2o3/POVNPpQheCDLDOYyc40jmFdGG8vlXs7Yz88j+Z2u3OD+SY9X33lMQooZnWW8ZkTqOsmhhuCOFjAn3Yk33AfTETn/AOyCfyk2zEQQNWS98IiJGFYfN11JV2lvdmLnZYtVSfwl2Ni752oZB7pHUeOaLcCNtxQiJ9aEHKbSJ0DwJYqD0LBasjQg5Qoj2L113GHnZXQd8qCLlmTvyR0fBA18XPsTj28x0Xujtol8QtuCj9ABSeX7KkAjwwI6dgq3X/b/7TBlLdPVvYwv96y4XCm2exgZggU/uX3CAEsCCacwARAc3akK+ALjgYzu5fto3U18="
    # GITHUB_ACCESS_TOKEN=[secure]
    - secure: "srBWAyZIY44XzHSaWqJq4T70KSopqa1sa6fcPQeIp2lQcog9F2PWQX+0bS7q1USDEasvfWy+kwyZ4OAff+BbzBtz4P+jSDsAN7jGOe2C9YFchq1eTaxM9Uty4V6HRe5zZGgFbleM2W5A5jfnWwiwX3PnCDXE2T1xNmaGY4TrVFulQZ2oEJJMHXf6fhqjEa2JudyRpNzle2ijPxOIRXa/g6+HfSjQW/Y0OHybi7wMVJV2mRM+A1B75z1DoowAZfYDHwSgjQs0r3NCQJCffBJ+lJLl+gl47IRnu0E+y7tscgWjxXlLIPX9SQBiwE9nrcErZwL/QJLBhZMtKofDzZAiZ7xW5FtS8qD6Bho0Sc+qG/BzHRen4eVvTDGPGDNCyr98xaAeLgu0ohPzKLjblgXc/gLMoFly3QDdx1q1wjJBVKZezJhbtOxgjFYGYAuH/gtvkBhzpbhhk3MxGl6bP0ksUf4DB5lhjVVHoccRfDFN14ZDoIMUYF+mwqybdE7WIoHp0JVVbHSMB5JwrUutV0/y7YcwnTRaBGpFB9kLaJheNgl5F74CFiHwns+a4Xl54cvawydWrgBCKtJUx4Bz8tY2muh7gGWAyQLJo/8T74k5e05MkpP9MEwejphFh1Ja0jFP1HlZRj8myZPkmqbk3nmZmIysRV0ULPEExSKH3EKVqWM="
    # SNYK_API_TOKEN=[secure]
    - secure: "JVaYl9zH8UhAoWwQ9/fgY9suezRkYutPazkQjaoFS5oZHLn0CucNQdXDNEslyLMfRYpAsjqoXRjFI8bY4md+8/CIdBiBmfMEVX+Zwue7GrpqqovqW6gIlNnmMX4Xzd1R0sgGzr6cZr2SaAv3ryvN/RX/JzHVOSDjlrZIWrj4GznDLehXZieQC1A4H1VjzHazUSJ5PpQ6Vl3F0rW7MqHyaO6O1EMkHv2LwX6Ojp79d3MwyggjUB2VudnXyOYypP6JKGWv0cMV8N8YbyJM+c8nkxr41EV4lM7Z6s7aA+Z0G00A8V8YSsdLOvh045cxOA7ehu0EWIXxl4umR/V5FzN504YyM0a3ILo9/uan6esFRZGBftY1H5Aww0fw6yORkA2oZhB/fClLNhrNzGl2F//BgVY9yjsPI7vCeX3kZNsf8AtMVMeEENnYqfxv334PNVuddkBE3+XmqJQ9Kxz4nsh7AmMwHx/EnIfpi16YI2xJkb/kdnhb8P9BDUpjXd37tIVvNRdVGKPwzvjCkv4Gl7ZfEetsi904io9sj3KNCi3FQSUJrWb/ck7LGSsdgt0thKvjjavOvJC19FWq97YuU2ouV5+MFnQCCbNrF/62RVhmso7MZEdxewQLOnKKJomPuiHcjeQaDvkOepn7L8ost1OLq5jhh51Zv6gpoCkYc8/jlqA="
    # ATM_CERTIFICATE=[secure]
    - secure: "obJbDccUmdb5BV0q9eup6qutmT1z9gBo7JEZr33OSCMb4GQGHUmpANLsxcFGwh9NZdoRGGOn1ZNHK28O2oLdIVROTKxKDDNNNyyRl8fnrhhsQRa/L4MNttsrv4J779R0dhMSRgqXXJN5urAYCHMt5A7ZVA48p6KKAsE+H8ukHnHzN7Q9KD67cGm5jml780iy6crzGD9mnZXhjmPp2LTmGclocj6KkRr1p35Ij88/UFtVjw/I0oVmxhG4fhgy52403q1Fb/IEVJQNt1bNpewPiTzKUkZiMM+flOso2A/Rc6Uf5z+6nooGCCu/UbCIRdu2cOGjlORS1vvYppfedxoLX0mwmMEloJ7gLh8DO+hEfocMf24ktT1DoXuOInbXdF5wSzXMiJ+avP+7fB2kveHZNJ/tUiDzZ63dPH7FXr+kXKrWHrTne8MBoUOf8C+/GYmmoEHrzTmn1CvL0t6z7cCzi6xVNNvmzgz+mwxo8NYCT8wYxLtVNwY4Znsx5skMBd6TFumCUZAy3qfCnA2C6lhYleQoJ7aiek7tCJO4czZzGlBJCyYzioRHpbfdC9oMETwEmwFSBwGgBAPjDNcYeBJXz2BrnzWiRxi+tjNDYx7fMMXJF3xDY9jgNGlyhbYr+dIE3D4w8XuXNhlacO4t5SSlfcl4p8Ag4SB4RECwrrf+Ixk="

stage: "Run Unit Tests :clipboard:"
node_js:
  - 6
  - 8
before_install:
  - source bin/deploy/init.sh
script:
  - recink run unit -c recink-codeclimate -c recink-snyk

jobs:
  include:
    - stage: "Deploy To :cloud:"
      node_js: 6
      script:
        - if [ ${ALLOW_DEPLOY} == 1 ]; then node bin/deploy; else echo "Skipping deploy"; fi
      after_failure:
        - deepify undeploy src --loglevel=debug

    - stage: "Run e2e Tests :clipboard:"
      node_js: 8
      script:
        - if [ ${ALLOW_DEPLOY} == 1 ]; then recink run e2e; else echo "Skipping e2e tests"; fi
      # addons:
      #   firefox: 'latest'
      #   chrome: 'beta'
      #   apt:
      #     packages:
      #       - xvfb
      # install:
      #   - 'export DISPLAY='':99.0'''
      #   - 'Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &'

    - stage: "Page speed :rocket:"
      node_js: 6
      script:
        - if [ ${ALLOW_DEPLOY} == 1 ]; then recink run unit -s emit -c recink-pagespeed; else echo "Skipping pagespeed"; fi