---
engines:
  duplication:
    config:
      languages:
        javascript:
          mass_threshold: 350
exclude_paths:
  - "**/bin"
  - "**/test"
  - "**/tests"
  - "**/tmp"
  - "**/vendor"
  - "**/aws-262"
  - "**/.idea"
  - "**/assets"
  - "**/www.washingtonpost*"
  - "**/www.bloomberg*"
  - "**/www.nytimes*"
  - "**/wapost*"
  - "**/bloomberg*"
  - "**/nytimes*"
  - "**/atm-build"
  - "**.spec.js"
  - "**.min.js"
  - "**.min.css"
  - "**/frontend/_build/"
  - "**/dist"
  - "**/node_modules"
  - "**/packages"
  - "**/font-awesome.css"
  - "**/materialdesignicons.css"
  - "**/DeepFramework.js"
  - "**/deep-framework.js"
  - "**/atm-core/frontend/css/main.css"
  - "**/src/deep-root-*"
  - "**/carousel.js"
  - "**/contact.js"
  - "**/gtm.js"
  - "**/jquery.js"
  - "**/jquery.noty.packaged.js"
  - "**/jquery.vide.js"
